# Generated by Django 4.1.6 on 2023-02-04 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterField(
            model_name='user',
            name='location',
            field=models.ManyToManyField(blank=True, null=True, to='users.location'),
        ),
    ]
